[preload  storage="./data/fgimage/default/0/stop.png"  ]
[preload  storage="./data/bgimage/b4.png"  ]
[preload  storage="./data/fgimage/default/mu/mu1.png"  ]
[preload  storage="./data/bgimage/dark.png"  ]
[preload  storage="./data/fgimage/default/mu/mu2.png"  ]
[preload  storage="./data/fgimage/default/mu/mu3.png"  ]
[preload  storage="./data/fgimage/default/mu/mu4.png"  ]
[preload  storage="./data/fgimage/default/0/dark.png"  ]
[return]