[preload  storage="./data/bgimage/hintback.png"  ]
[preload  storage="./data/fgimage/default/hint/hyo.png"  ]
[preload  storage="./data/fgimage/chara/6/xxb_0019.png"  ]
[preload  storage="./data/fgimage/chara/6/xxb_0018.png"  ]
[preload  storage="./data/fgimage/chara/6/xxb_0021.png"  ]
[preload  storage="./data/fgimage/chara/6/xxb_0020.png"  ]
[preload  storage="./data/fgimage/chara/6/xxb_0022.png"  ]
[preload  storage="./data/fgimage/default/0/dark.png"  ]
[preload  storage="./data/bgimage/si.png"  ]
[return]